
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>


<form action="https://gw.sandbox.gopay.com/gw/v3/d0cc035dbbac4baf5d7c02433aa75575" method="post">
  <button name="pay" type="submit">Zaplatit</button>
</form>
    
    </body>
</html>



