<!-- Pohled pro administraci -->

<?php
// Nastavení časové zóny
date_default_timezone_set('Europe/Prague');
?>

<div class="row pt-5 pb-5 text-center text-white bg-primary">
  <div class="col-12" >
    <h1 class="text-large">Správa Transakcí</h1>
  </div>

</div>

<h1 class="text-center pt-3 pb-3">Informace o Transakcích</h1>
<!-- Záhlaví tabulky -->
<div class="d-flex  table-responsive-xl mx-5">
    <table class="table fixed-table-body table-striped table-sm table-hover text-center rounded-3 overflow-hidden shadow mx-5">
      <thead class="table-dark">
        <tr>
          <th>Číslo transakce</th>
          <th>Oddělení</th>
          <th>Jméno</th>
          <th>Příjmení</th>
          <th>Email</th>
          <th>Telefon</th>
          <th>Město</th>
          <th>Ulice</th>
          <th>Číslo popisné</th>
          <th>PSČ</th>
          <th>Způsob platby</th>
          <th>Částka</th>
          <th>Stav</th>
          <th>Čas vytvoření</th>
          <th>Čas zaplaceni</th>
          <th>Request</th>
        </tr>
      </thead>
  
      <tbody>
        <!-- Výpis z databáze -->
        <?php foreach ($transakce as $radek){ ?>
        <tr>
          <td><?= $radek['id_transakce']; ?></td>
          <td><?= $radek['oddeleni']; ?></td>
          <td><?= $radek['jmeno']; ?></td>
          <td><?= $radek['prijmeni']; ?></td>
          <td><?= $radek['email']; ?></td>
          <td><?= $radek['telefon']; ?></td>
          <td><?= $radek['mesto']; ?></td>
          <td><?= $radek['ulice']; ?></td>
          <td><?= $radek['CP']; ?></td>
          <td><?= $radek['PSC']; ?></td>
          <td><?= $radek['zpusob_platby']; ?></td>
          <td><?= $radek['castka'] . "Kč"; ?></td>
          <td><?= $radek['stav']; ?></td>
          <td><?=date("j.n.Y H:i:s", strtotime($radek['cas_vytvoreni'])); ?></td>
          <td><?php if($radek["cas_zaplaceni"] != NULL) echo(date("j.n.Y H:i:s", strtotime($radek['cas_zaplaceni']))); ?></td>
          <td><a href="<?=$this->view?>?request=<?= $radek["id_transakce"] ?>" class="link-underline">request</a></td>
        
        </tr>
        <?php } ?>
      </tbody>
    </table>
</div>
