<!-- Formulář pro PaymentDemo -->
<div class="row pt-5 pb-5 text-center text-white bg-primary">
    <div class="col-12" >
        <h1 class="text-large" >Formulář Zaplacení</h1>
    </div>
</div>

<div class="container" >
    <div class="row mt-3 pb-5"> 
        <div class="col-xl-1">
            
        </div>
        <div class="col-xl-10 border rounded-5 p-3 shadow">
            
            <div class="row text-center my-3">
        
                <h2>Dodací údaje:</h2>
            </div>
            <div class="border"></div>
            <form method="POST" action="paymentdemo">
                <input type="text" name="oddeleni" id="oddeleni" required value="platebni_brana" hidden>


                <div class="row mt-3">
                    <div class="form-group col-md-6">
                        <label for="jmeno" class="form-label">Jméno: </label>
                        <input type="text" name="jmeno" id="jmeno"  required class="form-control ">
                    </div>
                    <div class="form-group col-md-6">
                        <label for="prijmeni" class="form-label">Příjmení: </label>
                        <input type="text" name="prijmeni" id="prijmeni"  required class="form-control">
                    </div>
                </div>
                
                <div class="row mt-3">
                    <div class="form-group col-md-4">
                        <label for="email" class="form-label">Email: </label>
                        <input type="email" name="email" id="email"  required class="form-control">
                    </div>
                        <div class="form-group col-md-4">
                            <label for="telefon" class="form-label">Telefonní číslo: </label>
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <div class="input-group-text">+</div>
                                    </div>
                                    <input type="tel" name="telefon" id="telefon" required class="form-control">
                                </div>
                        </div>
                        <div class="form-group col-md-4">
                        <label for="castka" class="form-label">Částka: </label >
                        <input type="number" name="castka" id="castka"  required class="form-control">
                    </div>
                </div>
                
                <div class="row mt-3">
                    <div class="form-group col-md-4">
                        <label for="mesto" class="form-label">Město: </label>
                        <input type="text" name="mesto" id="mesto" required class="form-control">
                    </div>
                    <div class="form-group col-md-4">
                        <label for="ulice" class="form-label">Ulice: </label>
                        <input type="text" name="ulice" id="ulice" required class="form-control">
                    </div>
                    <div class="form-group col-md-2">
                        <label for="CP" class="form-label">Číslo popisné: </label>
                        <input type="number" name="CP" id="CP" required class="form-control">
                    </div>
                    <div class="form-group col-md-2">
                        <label for="PSC" class="form-label">PSČ: </label>
                            <input type="number" name="PSC" id="PSC" required class="form-control">
                        </div>
                    <!-- Výpis erroru -->
                     <?php if(strlen($this->data["error"]) != 0){
                    ?>
                    <div class="text-center  mt-2">
                        <p class="text-danger fw-semibold fst-italic  "><?=$this->data["error"]?></p>
                    </div>
                        <?php
                    }
                    ?>
                </div>
                <div class="border mt-4"></div>
                <div class="row mt-4 mb-2">
                    <div class="col-sm-12 d-flex justify-content-between  ">
                        <a href="mainpage" class="btn btn-primary btn-formular">Zpět</a>
                        <button type="submit" class="btn btn-primary btn-formular">Pokračovat</button>
                    </form>
                    </div>
                </div>   
        </div>    
        <div class="col-xl-1">
            
        </div>
    </div>
</div>