<!-- Základní HTML struktura -->

<!DOCTYPE html>
<html lang="cs">
<head>
    <base href="/">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Integrace platební brány GoPay</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="style.css">

    <!-- připojení fontu -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@500&display=swap" rel="stylesheet">


</head>
<body>
    <!-- Připojení Bootstrapu  -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script>

        // Nastavení zvýrazněného prvku v navigaci
        window.addEventListener('load', function () {
        let url = window.location.href;
        url = url.split("/");

        const element = document.getElementById(url.pop());

        if (element != null){
            element.setAttribute("class"," nav-item nav-link active")
        }
        })
        
    </script>

<!-- Navigace -->
<div class="container-fluid ">
        <div class="row">
                <nav class="navbar navbar-expand navbar-light navbar- bg-light text-uppercase fw-bold ">
                    <div class="nav navbar-nav text-nav">
                        <a id="mainpage" class="nav-item nav-link" href="mainpage" >Úvod</a>
                        <?php 
                        if(($_SESSION["prihlasen"] == true)){
                            ?>  <a  id="administration" class="nav-item nav-link" href="administration">Správa</a> 
                        <?php } ?>
                        <div class="border"></div>
                            <a id="paymentdemo" class="nav-item nav-link" href="paymentdemo">Zaplatit Demo</a>
                    </div>
                    <div class="nav navbar-nav ms-auto text-nav">
            
                    
                    <?php 
                    if(($_SESSION["prihlasen"] == false)){
                        ?>  <a class="nav-item nav-link " href="login">Přihlásit</a> <?php
                    }
                    else {
                        ?>  <a class="nav-item nav-link navbar-end" href="logout">Odhlásit</a> <?php
                    }
            
                    ?>
                    </div>
                </nav>
        </div>

      
        
    </div>
    <!-- Výpis zpráv -->
    <div class="container-fluid">
    
        <div 
            <?php 
            if(isset($messsages))
            foreach ($messsages as $message) { ?>
                <p class="<?= $message["type"] ?>">
                    <?= $message["message"] ?>
                </p>
            <?php } ?>
        </div>
    

    
<?php
    // výpis aktuálního pohledu
    $this->controller->printView();

        
   ?>
   </div>
</body>
</html>