<!DOCTYPE html>
<html lang="cs">
<head>
    <base href="/">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Integrace platební brány GoPay</title>
</head>
<body>
    </div>
    <nav>
        <ul>
            <li><a href="uvod">Úvod</a></li>
            <li><a href="login">Správa</a></li>
            <li><a href="zaplatit">Zaplatit</a></li>
        </ul>
    </nav>

    <div >
        <?php 
        if(isset($messsages))
        foreach ($messsages as $message) { ?>
            <p class="<?= $message["type"] ?>">
                <?= $message["message"] ?>
            </p>
        <?php } ?>
    </div>

<?php
        $this->controller->printView();
        
   ?>
   
</body>
</html>