
<?php
require("htmlTop.php");
    
    
?>



<h2>vítej ve spravě databáze</h2>
<form  method="post">
    <input type="password" name="heslo" id="heslo">
    <label for="heslo">zadej heslo</label>

    <input type="submit" value="Prihlasit se">

</form>

<?php
if(isset($_POST["heslo"])){
    if(strcmp($_POST["heslo"],"th0") == 0){
        $_SESSION["sprava"] = 1;
        header("Location: sprava.phtml");
    }
}





require("htmlBottom.html");
?>







