
<h2>Přihlášení do systému</h2>
<form  method="post">
    <input type="text" name="jmeno" id="jmeno" required>
    <label for="jmeno">zadej jmeno</label>

    <input type="password" name="heslo" id="heslo" required>
    <label for="heslo">zadej heslo</label>

    <input type="submit" value="Prihlasit se">
    <p></p>
    <?php
    // if(isset($this->data["error"]))
    if(strlen($this->data["error"]) != 0){
        ?>
        <p><?=$this->data["error"]?></p>
        <?php
    }
    ?>

</form>







