<div class="row pt-5 pb-5 text-center text-white bg-primary">
    <div class="col-12" >

        <h1 class="text-large" >Přihlášení Do Systému</h1>
    </div>
</div>



<div class="container">
    <div class="row mt-3 "> 
        <div class="col-xl">
            
        </div>
        <div class="col-xl-4 border rounded-5 p-4">
            
            <div class="row text-center mb-2">
                <h2>Přihlásit se</h2>
            </div>
            <div class="border "></div>
            <form  method="post" >
                <div class=" row mt-3">
                    <label for="jmeno" class="form-label">Zadej jméno: </label>
                    <input type="text" name="jmeno" id="jmeno" required class="form-control" placeholder="Jmeno">
                </div>
        
                <div class=" row mt-3">
                    <label for="heslo" class="form-label">Zadej heslo: </label>
                    <input type="password" name="heslo" id="heslo" required class="form-control" placeholder="Heslo">
                </div>
                <?php
                // if(isset($this->data["error"]))
                if(strlen($this->data["error"]) != 0){
                    ?>
                    <div class="text-center  mt-2">
                        <p class="text-danger fw-semibold fst-italic  "><?=$this->data["error"]?></p>
                    </div>
                        <?php
                    }
                    ?>
                <div class="row mt-4 mb-2" text-center >
                    <input type="submit" value="Prihlasit se" class="btn btn-primary ">
                </div>
            </form>
           
        </div>    
        <div class="col-xl">
            
        </div>
    </div>
</div>








