<?php
    // Nastavení časové zóny
    date_default_timezone_set('Europe/Prague');
?>

<div class="row pt-5 pb-5 text-center text-white bg-primary">
  <div class="col-12" >
    <h1 class="text-large">Správa Oddělení</h1>
  </div>
</div>

<!-- Přidání oddělení -->
<div class="container">
    <div class="row">
        <div class="col-12">
            <h1 class="text-center pt-3 pb-3">Přidání oddělení</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <form method="post" action="adddepartment">
                <div class="form-group">
                    <label for="nazev">Název oddělení</label>
                    <input type="text" class="form-control" id="nazev" name="nazev" required>
                </div>
                <div class="form-group">
                    <label for="url">URL</label>
                    <input type="text" class="form-control" id="url" name="url">
                </div>
                <div class="form-group">
                    <label for="notification_url">Notifikační URL</label>
                    <input type="text" class="form-control" id="notification_url" name="notification_url">
                </div>
                <div class="form-group>
                    <label for="api_token">API token</label>
                    <input type="text" class="form-control" id="api_token" name="api_token">
                </div>
                <input type="submit" class="btn btn-primary" name="submit" value="Přidat">
            </form>
        </div>
    </div>
</div>


<h1 class="text-center pt-3 pb-3">Informace o Oddělení</h1>
<!-- Záhlaví tabulky -->
<div class="d-flex  table-responsive-xl mx-5">
    <table class="table fixed-table-body table-striped table-sm table-hover text-center rounded-3 overflow-hidden shadow mx-5">
      <thead class="table-dark">
        <tr>
          <th>oddělení</th>
          <th>URL</th>
          <th>Notifikační URL</th>
          <th>API token</th>
          <th>Upravy</th>
        </tr>
      </thead>
  
      <tbody>
        <!-- Výpis z databáze -->
        <?php foreach ($oddeleni as $radek){ ?>
        <tr>
            <td><?= $radek['nazev']; ?></td>
            <td><?= $radek['url']; ?></td>
            <td><?= $radek['notification_url']; ?></td>
            <td><?= $radek['api_token']; ?></td>
            <td>
                <a href="editdepartment?id=<?= $radek['nazev'] ?>" class="btn btn-primary">Upravit</a>
                <a href="deletedepartment?id=<?= $radek['nazev'] ?>" class="btn btn-danger">Smazat</a>
        </tr>
        <?php } ?>
      </tbody>
    </table>
</div>