<!-- Pohled pro výpis requestů -->
<div class="row pt-5 pb-5 text-center text-white bg-primary">


    <div class="col-12" >

        <h1 class="text-large" >Api token</h1>
    </div>
</div>

<div class="container">
    <div class="row mt-3 "> 
        <div class="col-xl-1">
            
        </div>
        <div class="col-xl-10 border rounded-5 p-3 shadow">
            
        <div class="form-group col-md-12">
            <label for="api_token" class="form-label">Api token: </label>
            <textarea class="form-control" id="api_token" rows="7" disabled><?=$this->data["api_token"]?></textarea>
        </div>
        </div>    
        <div class="col-xl-1">
            
        </div>
    </div>
</div>