<!-- Pohled pro výpis requestů -->
<div class="row pt-5 pb-5 text-center text-white bg-primary">


    <div class="col-12" >

        <h1 class="text-large" >Request</h1>
    </div>
</div>

<div class="container">
    <div class="row mt-3 "> 
        <div class="col-xl-1">
            
        </div>
        <div class="col-xl-10 border rounded-5 p-3 shadow">
            
        <div class="form-group col-md-12">
            <label for="request" class="form-label">Request: </label>
            <input type="text" name="request" id="request" value="<?=$this->data["request"]?>" required class="form-control" disabled >
        </div>
        </div>    
        <div class="col-xl-1">
            
        </div>
    </div>
</div>