<!-- TODO values nahaze do tohodle formulare -->
<form method="post" action="upravit">
    
        <label for="first_name">Jméno: </label><input type="text" name="first_name" id="first_name"><br>
        <label for="last_name">Příjmení: </label><input type="text" name="last_name" id="last_name"><br>
        <label for="email">Email: </label><input type="email" name="email" id="email"><br>
        <label for="phone_number">Telefonní číslo: </label><input type="tel" name="phone_number" id="phone_number">
    
    
        <label for="street">Ulice: </label><input type="text" name="street" id="street" value=""><br>
        <label for="city">Město: </label><input type="text" name="city" id="city"><br>
        <label for="postal_code">PSČ: </label><input type="number" name="postal_code" id="postal_code">
    
    
        <label for="amount">Částka: </label><input type="number" name="amount" id="amount" required><br>
    

    <button type="submit">Pokracovat</button>
</form>