<!-- TODO values nahaze do tohodle formulare -->
<form method="POST" action="upravit">

    <label for="id_transakce">ID: </label>
    <input type="number" name="id_transakce" id="id_transakce" value="<?=$this->data["transakce"]["id_transakce"]?>" required readonly><br>
    
    <label for="oddeleni">Oddělení: </label>
    <input type="text" name="oddeleni" id="oddeleni" value="<?=$this->data["transakce"]["oddeleni"]?>" required><br>
    
    <label for="jmeno">Jméno: </label>
    <input type="text" name="jmeno" id="jmeno" value="<?=$this->data["transakce"]["jmeno"]?>" required><br>
    <label for="prijmeni">Příjmení: </label>
    <input type="text" name="prijmeni" id="prijmeni" value="<?=$this->data["transakce"]["prijmeni"]?>" required><br>
    <label for="email">Email: </label>
    <input type="email" name="email" id="email" value="<?=$this->data["transakce"]["email"]?>" required><br>
    <label for="telefon">Telefonní číslo: </label>
    <input type="tel" name="telefon" id="telefon" value="<?=$this->data["transakce"]["telefon"]?>" required>


    <label for="ulice">Ulice: </label>
    <input type="text" name="ulice" id="ulice" value="<?=$this->data["transakce"]["ulice"]?>" required><br>
    <label for="mesto">Město: </label>
    <input type="text" name="mesto" id="mesto" value="<?=$this->data["transakce"]["mesto"]?>" required><br>
    <label for="PSC">PSČ: </label>
    <input type="number" name="PSC" id="PSC" value="<?=$this->data["transakce"]["PSC"]?>" required>
    <label for="CP">Číslo popisné: </label>
    <input type="number" name="CP" id="CP" value="<?=$this->data["transakce"]["CP"]?>" required>
    


    <label for="castka">Částka: </label>
    <input type="number" name="castka" id="castka" value="<?=$this->data["transakce"]["castka"]?>" required><br>

    <label for="zpusob_platby">Způsob platby: </label>
    <input type="text" name="zpusob_platby" id="zpusob_platby"value="<?=$this->data["transakce"]["zpusob_platby"]?>"><br>
    <label for="zaplaceno">Zaplaceno: </label>

    <Select name="zaplaceno" id="zaplaceno"  required >
                <?=$this->data["transakce"]["zaplaceno"]?>
    </Select>

    <label for="cas_vytvoreni">Čas Vytvoření: </label>
    <input type="text" name="cas_vytvoreni" id="cas_vytvoreni" value="<?=$this->data["transakce"]["cas_vytvoreni"]?>" required readonly><br>


    <label for="cas_zaplaceni">Čas Zaplacení: </label>
    <input type="text" name="cas_zaplaceni" id="cas_zaplaceni" value="<?=$this->data["transakce"]["cas_zaplaceni"]?>" readonly><br>



    <button href="sprava">Zpět</button>
    <button type="submit">Změnit</button>
</form>