<script>

window.addEventListener("DOMContentLoaded",function () {
    var zaplacenoValue;

    zaplaceno = document.querySelector("#zaplaceno");
    zaplacenoValue = zaplaceno.value;
    // nejaka funkce, ktera skryje ty dva prvky
    console.log(zaplacenoValue);
    document.querySelector("#zaplaceno").addEventListener("change", function() {
        // console.log(this.value);
        zaplacenoValue = this.value;
        // Get all elements with the class name 'mizejici'.
    var elements = document.querySelectorAll(".mizejici");

        // Loop through each element and hide or show it based on zaplacenoValue.
        elements.forEach(function(element) {
            if (zaplacenoValue === "0") {
                // If zaplacenoValue is "1", hide the element.
                element.style.display = 'none';
            } else {
                // Otherwise, show the element.
                element.style.display = 'block';
            }
        });
    });
})
</script>
<div class="row pt-5 pb-5 text-center text-white bg-primary">


    <div class="col-12" >

        <h1 class="text-large" >Úprava záznamu</h1>
    </div>
</div>

<div class="container">
    <div class="row mt-3 "> 
        <div class="col-xl-1">
            
        </div>
        <div class="col-xl-10 border rounded-5 p-3">
            
            <div class="row text-center my-3">
        
                <h2>Číslo Objednávky: <?=$this->data["transakce"]["id_transakce"]?></h2>
            </div>
            <div class="border"></div>
            <form method="POST" action="upravit">

                <input type="hidden" name="id_transakce" id="id_transakce" value="<?=$this->data["transakce"]["id_transakce"] ?>">
                <input type="hidden" name="byla_zaplacena" id="byla_zaplacena" value="<?=$this->data["transakce"]["byla_zaplacena"] ?>">
                <div class="row mt-3">
                    <div class="form-group col-md-6">
                        <label for="jmeno" class="form-label">Jméno: </label>
                        <input type="text" name="jmeno" id="jmeno" value="<?=$this->data["transakce"]["jmeno"]?>" required class="form-control ">
                    </div>
                    <div class="form-group col-md-6">
                        <label for="prijmeni" class="form-label">Příjmení: </label>
                        <input type="text" name="prijmeni" id="prijmeni" value="<?=$this->data["transakce"]["prijmeni"]?>" required class="form-control">
                    </div>
                </div>
                
                <div class="row mt-3">
                    <div class="form-group col-md-6">
                        <label for="email" class="form-label">Email: </label>
                        <input type="email" name="email" id="email" value="<?=$this->data["transakce"]["email"]?>" required class="form-control">
                    </div>
                        <div class="form-group col-md-6">
                            <label for="telefon" class="form-label">Telefonní číslo: </label>
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <div class="input-group-text">+</div>
                                    </div>
                                    <input type="tel" name="telefon" id="telefon" value="<?=$this->data["transakce"]["telefon"]?>" required class="form-control">
                                </div>
                        </div>
                </div>
                
                <div class="row mt-3">
                    <div class="form-group col-md-4">
                        <label for="mesto" class="form-label">Město: </label>
                        <input type="text" name="mesto" id="mesto" value="<?=$this->data["transakce"]["mesto"]?>" required class="form-control">
                    </div>
                    <div class="form-group col-md-4">
                        <label for="ulice" class="form-label">Ulice: </label>
                        <input type="text" name="ulice" id="ulice" value="<?=$this->data["transakce"]["ulice"]?>" required class="form-control">
                    </div>
                    <div class="form-group col-md-2">
                        <label for="CP" class="form-label">Číslo popisné: </label>
                        <input type="number" name="CP" id="CP" value="<?=$this->data["transakce"]["CP"]?>" required class="form-control">
                    </div>
                    <div class="form-group col-md-2">
                        <label for="PSC" class="form-label">PSČ: </label>
                            <input type="number" name="PSC" id="PSC" value="<?=$this->data["transakce"]["PSC"]?>" required class="form-control">
                        </div>
                </div>
                    
                
                <div class="row mt-3">
                    <div class="form-group col-md-6">
                        <label for="oddeleni" class="form-label">Oddělení: </label>
                        <input type="text" name="oddeleni" id="oddeleni" value="<?=$this->data["transakce"]["oddeleni"]?>" required class="form-control">
                    </div>
                    <div class="form-group col-md-6">
                        <label for="castka" class="form-label">Částka: </label>
                        <input type="number" name="castka" id="castka" value="<?=$this->data["transakce"]["castka"]?>" required class="form-control">
                    </div>
                </div>
                
                <div class="row mt-3">
                    <div class="form-group col-md-6">
                        <label for="cas_vytvoreni" class="form-label">Čas Vytvoření: </label>
                        <input type="text" name="cas_vytvoreni" id="cas_vytvoreni" value="<?=$this->data["transakce"]["cas_vytvoreni"]?>" required readonly class="form-control">
                    </div>
                    <div class="form-group col-md-6">
                        <label for="zaplaceno" class="form-label">Zaplaceno: </label>
                        <Select name="zaplaceno" id="zaplaceno"  required class="form-select">
                            <?=$this->data["transakce"]["zaplaceno"]?>
                        </Select>
                    </div>
                </div>
                <div class="row mt-3">
                    <div class="form-group col-md-6">
                        <label for="cas_zaplaceni" class="form-label mizejici">Čas Zaplacení: </label>
                            <input type="text" name="cas_zaplaceni" id="cas_zaplaceni" value="<?=$this->data["transakce"]["cas_zaplaceni"]?>" readonly class="form-control mizejici">
                    </div>
                    <div class="form-group col-md-6">
                        <label for="zpusob_platby" class="form-label mizejici">Způsob platby: </label>
                        <input type="text" name="zpusob_platby" id="zpusob_platby"value="<?=$this->data["transakce"]["zpusob_platby"]?>" class="form-control mizejici">
                    </div>
                </div>
                <div class="row mt-3 mb-2">
                    <div class="col-sm-4">
                        <button href="sprava" class="btn btn-primary">Zpět</button>
                    </div>
                    <div class="col-sm-4">
                
                    </div>
                    <div class="col-sm-4 text-end  ">
                        <button type="submit" class="btn btn-primary ">Změnit</button>
                    </div>
                </div>   
            </form>
        </div>    
        <div class="col-xl-1">
            
        </div>
    </div>
</div>



    



